apiVersion: v1
kind: Service
metadata:
    name: "aksgitea-f301"
    labels:
        app: "aksgitea-f301"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksgitea-f301"