on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demogitopsacr01.azurecr.io
        username: ${{ secrets.acr_demogitopsacr01_username }}
        password: ${{ secrets.acr_demogitopsacr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/nginx" -f  "nginx/dockerfile" -t demogitopsacr01.azurecr.io/aksgitea:${{ github.sha }} --label dockerfile-path=nginx/dockerfile
        docker push demogitopsacr01.azurecr.io/aksgitea:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksgitea_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-git-ea8129 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-git-ea8129`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-git-ea8129
        container-registry-url: demogitopsacr01.azurecr.io
        container-registry-username: ${{ secrets.acr_demogitopsacr01_username }}
        container-registry-password: ${{ secrets.acr_demogitopsacr01_password }}
        secret-name: aksgiteadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-git-ea8129
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          demogitopsacr01.azurecr.io/aksgitea:${{ github.sha }}
        imagepullsecrets: |
          aksgiteadockerauth
